package com.noop.mgecg;

import android.Manifest; import android.app.Activity; import android.bluetooth.*; import android.bluetooth.le.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import android.view.*; import android.widget.*; import java.util.*; import java.util.UUID;

public class MainActivity extends Activity {
    private static final int REQ=42;
    private BluetoothAdapter adapter; private BluetoothGatt gatt; private BluetoothGattCharacteristic cmdWrite; private int seq=1;
    private TextView log; private Button scanBtn; private final UUID svc=UUID.fromString(Protocol.SERVICE), cmd=UUID.fromString(Protocol.CMD_WRITE), cmdN=UUID.fromString(Protocol.CMD_NOTIFY), dataN=UUID.fromString(Protocol.DATA_NOTIFY), eventN=UUID.fromString(Protocol.EVENT_NOTIFY), extraN=UUID.fromString(Protocol.EXTRA_NOTIFY);
    private final BluetoothGattCallback cb=new BluetoothGattCallback(){
        @Override public void onConnectionStateChange(BluetoothGatt g,int status,int state){ line("GATT state="+state+" status="+status); if(state==BluetoothProfile.STATE_CONNECTED){ if(Build.VERSION.SDK_INT>=21) g.requestMtu(247); g.discoverServices(); } }
        @Override public void onMtuChanged(BluetoothGatt g,int mtu,int status){ line("MTU="+mtu+" status="+status); }
        @Override public void onServicesDiscovered(BluetoothGatt g,int status){ line("services discovered status="+status); BluetoothGattService s=g.getService(svc); if(s==null){line("ERROR: fd4b service not found");return;} cmdWrite=s.getCharacteristic(cmd); subscribe(g,s.getCharacteristic(cmdN)); subscribe(g,s.getCharacteristic(eventN)); subscribe(g,s.getCharacteristic(dataN)); subscribe(g,s.getCharacteristic(extraN));
            if(cmdWrite!=null){ line("TX CLIENT_HELLO (confirmed write)"); cmdWrite.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT); cmdWrite.setValue(Protocol.clientHello()); g.writeCharacteristic(cmdWrite); } }
        @Override public void onCharacteristicWrite(BluetoothGatt g,BluetoothGattCharacteristic c,int status){ line("WRITE " + c.getUuid()+" status="+status); }
        @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] value){ line("RX "+shortUuid(c.getUuid())+"  "+Protocol.hex(value)+"  "+Protocol.frameSummary(value)); }
        @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c){ byte[] v=c.getValue(); onCharacteristicChanged(g,c,v); }
    };
    private String shortUuid(UUID u){return u.toString().substring(4,8);}
    private void subscribe(BluetoothGatt g,BluetoothGattCharacteristic c){ if(c==null)return; if(Build.VERSION.SDK_INT>=31 && checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)return; g.setCharacteristicNotification(c,true); BluetoothGattDescriptor d=c.getDescriptor(UUID.fromString("00002902-0000-1000-8000-00805f9b34fb")); if(d!=null){d.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE); g.writeDescriptor(d);} line("subscribe "+shortUuid(c.getUuid())); }
    private void send(int opcode,int arg,String name){ if(gatt==null||cmdWrite==null){line("NOT CONNECTED");return;} byte[] f=Protocol.labrador(opcode,arg,seq++); line("TX "+name+"  "+Protocol.hex(f)); cmdWrite.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT); cmdWrite.setValue(f); gatt.writeCharacteristic(cmdWrite); }
    @Override protected void onCreate(Bundle b){super.onCreate(b); adapter=((BluetoothManager)getSystemService(BLUETOOTH_SERVICE)).getAdapter(); buildUi(); requestPerms();}
    private void buildUi(){ LinearLayout root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(24,24,24,24); TextView title=new TextView(this); title.setText("NOOP MG ECG Experimental\nWHOOP 5/MG Labrador command probe"); title.setTextSize(20); root.addView(title,new LinearLayout.LayoutParams(-1,-2));
        scanBtn=new Button(this);scanBtn.setText("SCAN FOR WHOOP 5/MG");scanBtn.setOnClickListener(v->scan());root.addView(scanBtn);
        Button c1=btn("0x7B  SELECT_WRIST (RIGHT=0)",v->send(0x7B,0,"SELECT_WRIST")); root.addView(c1); Button c2=btn("0x7C  LABRADOR GENERATION START",v->send(0x7C,1,"LABRADOR_START"));root.addView(c2); Button c3=btn("0x7D  RAW SAVE ON",v->send(0x7D,1,"RAW_SAVE_ON"));root.addView(c3); Button c4=btn("0x8B  FILTERED ON",v->send(0x8B,1,"FILTERED_ON"));root.addView(c4); Button stop=btn("0x7C  LABRADOR STOP",v->send(0x7C,0,"LABRADOR_STOP"));root.addView(stop);
        log=new TextView(this);log.setTextIsSelectable(true);log.setTextSize(11); ScrollView sv=new ScrollView(this);sv.addView(log);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); }
    private Button btn(String t,View.OnClickListener l){Button b=new Button(this);b.setText(t);b.setOnClickListener(l);return b;}
    private void requestPerms(){ if(Build.VERSION.SDK_INT>=31){ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_SCAN);if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ);} }
    private void scan(){ if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED){requestPerms();return;} BluetoothLeScanner s=adapter.getBluetoothLeScanner(); line("SCANNING 10s..."); ScanFilter f=new ScanFilter.Builder().setServiceUuid(new android.os.ParcelUuid(svc)).build(); ScanSettings ss=new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(); s.startScan(Collections.singletonList(f),ss,sc);new Handler(Looper.getMainLooper()).postDelayed(()->{try{s.stopScan(sc);}catch(Exception ignored){} line("SCAN STOP");},10000); }
    private final ScanCallback sc=new ScanCallback(){@Override public void onScanResult(int type,ScanResult r){BluetoothDevice d=r.getDevice();line("FOUND "+d.getName()+" "+d.getAddress()+" RSSI="+r.getRssi()); if(gatt==null){if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)return;line("CONNECTING "+d.getAddress());gatt=d.connectGatt(MainActivity.this,false,cb,BluetoothDevice.TRANSPORT_LE);}}};
    private void line(String s){runOnUiThread(()->{String old=log==null?"":log.getText().toString(); if(old.length()>12000)old=old.substring(old.length()-9000); if(log!=null)log.setText(old+String.format("\n%tT  %s",new Date(),s));});}
    @Override protected void onDestroy(){try{if(gatt!=null)gatt.close();}catch(Exception ignored){}super.onDestroy();}
}
